type: object
description: Configuration of one deidentification strategy and a list of annotation types to apply it to.
properties:
  deidentificationStrategy:
    type: object
    description: The strategy used to de-identify the note's text. Only one field may be set.
    properties:
      maskingCharConfig:
        type: object
        description:
          Configuration for the masking char strategy. E.g. "John Smith lives at 123 Main St" -> "********* lives at
          ***********".
        properties:
          maskingChar:
            type: string
            description: Character used to mask annotated PII text.
            minLength: 1
            maxLength: 1
            default: "*"
      redactConfig:
        type: object
        description:
          Configuration for the redaction strategy. E.g. "John Smith lives at 123 Main St" -> "lives at".
      annotationTypeConfig:
        type: object
        description:
          Configuration for the "annotation type" strategy. E.g. "John Smith lives at 123 Main St" -> "[PERSON_NAME]
          lives at [PHYSICAL_ADDRESS]".
      dateOffsetConfig:
        type: object
        description:
          Configuration for the "date offset" strategy. E.g. "John Smith visited on 1 January 2020" -> "John Smith
          visited on 29 October 2025". Note, can only be set with the "text_date" annotation type.
        properties:
          offsetDays:
            type: integer
            description: Number of days by which to offset annotated dates.
  annotationTypes:
    type: array
    description: the types of annotations to which the de-identifer should apply the selected strategy
    items:
      type: string
      enum:
        - "text_physical_address"
        - "text_date"
        - "text_person_name"
