openapi: 3.0.3
info:
  version: 1.0.0
  title: NLP Sandbox Data Node API
  contact:
    name: The NLP Sandbox Team
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://nlpsandbox.github.io/nlpsandbox-schemas'
  license:
    name: Apache 2.0
    url: 'https://nlpsandbox.github.io/nlpsandbox-schemas/blob/develop/LICENSE'
  x-logo:
    url: 'https://nlpsandbox.github.io/nlpsandbox-schemas/logo.png'
  description: >
    # Overview

    The NLP Sandbox Data Node is a repository of data used to developed and
    benchmark NLP Tools like the Date Annotator and Person Name Annotator. The
    resources that can be stored in a Data Node are listed below:

    - Datasets
      - FHIR Stores
        - Patients
        - Clinical Notes
      - Annotation Stores
        - Annotations
tags:
  - name: Annotation
    description: Operations about annotations
  - name: AnnotationStore
    description: Operations about annotation stores
  - name: Dataset
    description: Operations about datasets
  - name: FhirStore
    description: Operations about FHIR stores
  - name: HealthCheck
    description: Operations about health checks
  - name: Note
    description: Operations about notes
  - name: Patient
    description: Operations about patients
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /datasets:
    $ref: 'paths/datasets.yaml'
  /datasets/{datasetId}:
    $ref: 'paths/datasets@{datasetId}.yaml'
  /datasets/{datasetId}/annotationStores:
    $ref: 'paths/annotationStores.yaml'
  /datasets/{datasetId}/annotationStores/{annotationStoreId}:
    $ref: 'paths/annotationStores@{annotationStoreId}.yaml'
  /datasets/{datasetId}/annotationStores/{annotationStoreId}/annotations:
    $ref: 'paths/annotations.yaml'
  /datasets/{datasetId}/annotationStores/{annotationStoreId}/annotations/{annotationId}:
    $ref: 'paths/annotations@{annotationId}.yaml'
  /datasets/{datasetId}/fhirStores:
    $ref: 'paths/fhirStores.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}:
    $ref: 'paths/fhirStores@{fhirStoreId}.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}/fhir/Patient:
    $ref: 'paths/patients.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}/fhir/Patient/{patientId}:
    $ref: 'paths/patients@{patientId}.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}/fhir/Note:
    $ref: 'paths/notes.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}/fhir/Note/{noteId}:
    $ref: 'paths/notes@{noteId}.yaml'
  /healthCheck:
    $ref: '../commons/paths/healthCheck.yaml'