openapi: 3.0.2
info:
  version: 1.0.0
  title: NLP Sandbox Data Node Schemas
  contact:
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://data2health.github.io/nlp-sandbox-data-node-schemas'
  license:
    name: Apache 2.0
    url: 'https://github.com/data2health/nlp-sandbox/blob/master/LICENSE'
  x-logo:
    url: 'https://data2health.github.io/nlp-sandbox-data-node-schemas/docs/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox Data Nodes.

    # Overview

    A NLP Sandbox Data Node is a repository of clinical notes that implements
    this OpenAPI specification so that other services in the NLP Sandbox
    ecosystem can access them. For example, a client requests data from a Data
    Node before passing them as input to an NLP Tool like a Date Annotator,
    Person Name Annotator, etc.

    For the sake of benchmarking NLP Tool, a Data Node can also give access to
    the gold standard that the NLP Tool is expected to infer (e.g. annotations).
tags:
  - name: Note
    description: Operations about clinical notes
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /annotations/dates:
    $ref: 'paths/annotations/dates.yaml'
  /health:
    $ref: '../commons/paths/health.yaml'
  /notes:
    $ref: 'paths/notes.yaml'
  /notes/{id}:
    $ref: 'paths/notes@{id}.yaml'