openapi: 3.0.2
info:
  version: 0.1.6
  title: NLP Sandbox Data Node API
  contact:
    name: The NLP Sandbox Team
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://Sage-Bionetworks.github.io/nlp-sandbox-schemas'
  license:
    name: Apache 2.0
    url: 'https://github.com/Sage-Bionetworks/nlp-sandbox/blob/main/LICENSE'
  x-logo:
    url: 'https://Sage-Bionetworks.github.io/nlp-sandbox-schemas/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox Data Nodes.

    # Overview

    A NLP Sandbox Data Node is a repository of clinical notes that implements
    this OpenAPI specification so that other services in the NLP Sandbox
    ecosystem can access them. For example, a client requests data from a Data
    Node before passing them as input to an NLP Tool like a Date Annotator,
    Person Name Annotator, etc.

    For the sake of benchmarking NLP Tool, a Data Node can also give access to
    the gold standard that the NLP Tool is expected to infer (e.g. annotations).
tags:
  # - name: Annotation
  #   description: Operations about annotations
  # - name: AnnotationStore
  #   description: Operations about annotation stores
  - name: Dataset
    description: Operations about datasets
  - name: Health
    description: Operations about service health
  - name: FhirStore
    description: Operations about FHIR stores
  # - name: NoteStore
  #   description: Operations about note stores
  # - name: Note
  #   description: Operations about notes
  - name: Service
    description: Operations about NLP services
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /datasets:
    $ref: 'paths/datasets.yaml'
  /datasets/{id}:
    $ref: 'paths/datasets@{id}.yaml'
  /datasets/{datasetId}/fhirStores:
    $ref: 'paths/fhirStores.yaml'

  # /datasets/{datasetId}/annotationStore:
  #   $ref: 'paths/annotationStores.yaml'
  # /datasets/{datasetId}/annotationStore/{id}:
  #   $ref: 'paths/annotationStores@{id}.yaml'
  # /datasets/{datasetId}/annotationStore/{storeId}/annotations:
  #   $ref: 'paths/annotations.yaml'
  # /datasets/{datasetId}/annotationStore/{storeId}/annotations/{id}:
  #   $ref: 'paths/annotations@{id}.yaml'
  # /datasets/{datasetId}/noteStore:
  #   $ref: 'paths/noteStores.yaml'
  # /datasets/{datasetId}/noteStore/{id}:
  #   $ref: 'paths/noteStores@{id}.yaml'
  # /datasets/{datasetId}/noteStore/{storeId}/notes:
  #   $ref: 'paths/notes.yaml'
  # /datasets/{datasetId}/noteStore/{storeId}/notes/{id}:
  #   $ref: 'paths/notes@{id}.yaml'
  /health:
    $ref: '../commons/paths/health.yaml'
  /service:
    $ref: '../commons/paths/service.yaml'