openapi: 3.0.2
info:
  version: 0.2.2
  title: NLP Sandbox Data Node API
  contact:
    name: The NLP Sandbox Team
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://nlpsandbox.github.io/nlpsandbox-schemas'
  license:
    name: Apache 2.0
    url: 'https://nlpsandbox.github.io/nlpsandbox-schemas/blob/develop/LICENSE'
  x-logo:
    url: 'https://nlpsandbox.github.io/nlpsandbox-schemas/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox Data Nodes.

    # Overview

    A NLP Sandbox Data Node is a repository of clinical notes that implements
    this OpenAPI specification so that other services in the NLP Sandbox
    ecosystem can access them. For example, a client requests data from a Data
    Node before passing them as input to an NLP Tool like a Date Annotator,
    Person Name Annotator, etc.

    For the sake of benchmarking NLP Tool, a Data Node can also give access to
    the gold standard that the NLP Tool is expected to infer (e.g. annotations).
tags:
  - name: Annotation
    description: Operations about annotations
  - name: AnnotationStore
    description: Operations about annotation stores
  - name: Dataset
    description: Operations about datasets
  - name: FhirStore
    description: Operations about FHIR stores
  - name: Note
    description: Operations about notes
  - name: Patient
    description: Operations about patients
  - name: Service
    description: Operations about this API service
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /datasets:
    $ref: 'paths/datasets.yaml'
  /datasets/{datasetId}:
    $ref: 'paths/datasets@{datasetId}.yaml'
  /datasets/{datasetId}/annotationStores:
    $ref: 'paths/annotationStores.yaml'
  /datasets/{datasetId}/annotationStores/{annotationStoreId}:
    $ref: 'paths/annotationStores@{annotationStoreId}.yaml'
  /datasets/{datasetId}/annotationStores/{annotationStoreId}/annotations:
    $ref: 'paths/annotations.yaml'
  /datasets/{datasetId}/annotationStores/{annotationStoreId}/annotations/{annotationId}:
    $ref: 'paths/annotations@{annotationId}.yaml'
  /datasets/{datasetId}/fhirStores:
    $ref: 'paths/fhirStores.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}:
    $ref: 'paths/fhirStores@{fhirStoreId}.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}/fhir/Patient:
    $ref: 'paths/patients.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}/fhir/Patient/{patientId}:
    $ref: 'paths/patients@{patientId}.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}/fhir/Note:
    $ref: 'paths/notes.yaml'
  /datasets/{datasetId}/fhirStores/{fhirStoreId}/fhir/Note/{noteId}:
    $ref: 'paths/notes@{noteId}.yaml'
  /service:
    $ref: '../commons/paths/service.yaml'