openapi: 3.0.2
info:
  version: 1.0.0
  title: NLP Sandbox Date Annotator API
  # termsOfService: 'https://data2health.github.io/nlp-sandbox-data-node-schemas/terms/'
  contact:
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://data2health.github.io/nlp-sandbox-schemas'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://data2health.github.io/nlp-sandbox-data-node-schemas/docs/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox Date Annotators.

    # Introduction
tags:
  - name: Date
    description: Operations about dates
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /dates:
    $ref: 'paths/dates.yaml'
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
