openapi: 3.0.2
info:
  version: 0.2.0
  title: NLP Sandbox Deidentifier API
  contact:
    name: The NLP Sandbox Team
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://Sage-Bionetworks.github.io/nlp-sandbox-schemas'
  license:
    name: Apache 2.0
    url: 'https://github.com/Sage-Bionetworks/nlp-sandbox/blob/main/LICENSE'
  x-logo:
    url: 'https://Sage-Bionetworks.github.io/nlp-sandbox-schemas/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers.

    # Overview

    TBA
tags:
  - name: DeidentifiedNotes
    description: Operations about deidentified notes
  - name: Service
    description: Operations about this API service
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /deidentifiedNotes:
    $ref: 'paths/deidentifiedNotes.yaml'
  /service:
    $ref: '../commons/paths/service.yaml'