openapi: 3.0.2
info:
  version: 1.0.0
  title: NLP Sandbox Physical Address Annotator API
  contact:
    name: The NLP Sandbox Team
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://Sage-Bionetworks.github.io/nlp-sandbox-schemas'
  license:
    name: Apache 2.0
    url: 'https://github.com/Sage-Bionetworks/nlp-sandbox/blob/main/LICENSE'
  x-logo:
    url: 'https://Sage-Bionetworks.github.io/nlp-sandbox-schemas/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox Physical Address Annotators.

    # Overview

    This NLP tool detects references of physical addresses in the clinical notes
    given as input and returns a list of physical address annotations.
tags:
  - name: Physical Address
    description: Operations about physical addresses
  - name: Health
    description: Operations about API health
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /physical-addresses:
    $ref: 'paths/physical-addresses.yaml'
  /health:
    $ref: '../commons/paths/health.yaml'