openapi: 3.0.2
info:
  version: 1.0.0
  title: NLP Sandbox Person Name Annotator API
  # termsOfService: 'https://data2health.github.io/nlp-sandbox-data-node-schemas/terms/'
  contact:
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://data2health.github.io/nlp-sandbox-schemas'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://data2health.github.io/nlp-sandbox-schemas/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox Person Name Annotators.

    # Overview

    This NLP tool detects references of person names in the clinical notes given
    as input and returns a list of person name annotations.
tags:
  - name: Person Name
    description: Operations about person names
  - name: Health
    description: Operations about API health
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /person-names:
    $ref: 'paths/person-names.yaml'
  /health:
    $ref: '../commons/paths/health.yaml'