get:
  tags:
    - Service
  summary: Get service information
  description: Get information about the service
  operationId: "service"
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Service.yaml
    '403':
      $ref: ../components/responses/Unauthorized.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml