name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      node_version: 12.x
    # strategy:
    #   matrix:
    #     node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js $node_version
      uses: actions/setup-node@v1
      with:
        node-version: $node_version
    - run: npm install
    - name: Lint OpenAPI specifications
      run: npx @redocly/openapi-cli lint
        openapi/data-node/openapi.yaml
        openapi/date-annotator/openapi.yaml
        openapi/person-name-annotator/openapi.yaml
        openapi/physical-address-annotator/openapi.yaml