name: ci

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  node_version: 12.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node_version }}
    - run: npm install
    - name: Lint openapi specifications
      run: npx @redocly/openapi-cli lint openapi/*/openapi.yaml

  build-and-publish:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - run: npm install -g @ga4gh/gh-openapi-docs
      # - name: Build full openapi specs and their docs
      #   run: npx @redocly/openapi-cli lint openapi/*/openapi.yaml